# Generated by Django 3.1.3 on 2020-11-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201112_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('auto_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('redlist_nsc', models.CharField(blank=True, max_length=255, null=True)),
                ('redlist_wang', models.CharField(blank=True, max_length=255, null=True)),
                ('redlist_wang_ass', models.CharField(blank=True, max_length=255, null=True)),
                ('redlist_chen', models.CharField(blank=True, max_length=255, null=True)),
                ('iucn_code', models.CharField(blank=True, max_length=255, null=True)),
                ('iucn_assessment', models.CharField(blank=True, max_length=255, null=True)),
                ('iucn_dateassessed', models.CharField(blank=True, max_length=255, null=True)),
                ('iucn_id', models.CharField(blank=True, max_length=255, null=True)),
                ('iucn_group', models.CharField(blank=True, max_length=255, null=True)),
                ('coa_redlist_code', models.CharField(blank=True, max_length=255, null=True)),
                ('coa_dateassessed', models.CharField(blank=True, max_length=255, null=True)),
                ('cites_code', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis_c', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('habitat_c', models.TextField(blank=True, null=True)),
                ('habitat', models.TextField(blank=True, null=True)),
                ('distribution_c', models.TextField(blank=True, null=True)),
                ('distribution', models.TextField(blank=True, null=True)),
                ('utility_c', models.TextField(blank=True, null=True)),
                ('utility', models.TextField(blank=True, null=True)),
                ('redlist2017', models.CharField(blank=True, max_length=10, null=True)),
                ('redlist2017_note', models.CharField(blank=True, max_length=100, null=True)),
                ('datelastmodified', models.CharField(blank=True, max_length=255, null=True)),
                ('lastmodifiedby', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'details',
                'managed': False,
            },
        ),
    ]
