# Generated by Django 3.1.3 on 2021-01-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewAlternativeNameC',
            fields=[
                ('name_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('alternative_name_c', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_alternative_name_c',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewApioutput',
            fields=[
                ('name_code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('genus', models.CharField(blank=True, max_length=80, null=True)),
                ('species', models.CharField(blank=True, max_length=100, null=True)),
                ('infraspecies_marker', models.CharField(blank=True, max_length=20, null=True)),
                ('infraspecies', models.CharField(blank=True, max_length=50, null=True)),
                ('infraspecies2_marker', models.CharField(blank=True, max_length=20, null=True)),
                ('infraspecies2', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.CharField(blank=True, max_length=150, null=True)),
                ('author2', models.CharField(blank=True, max_length=150, null=True)),
                ('is_accepted_name', models.IntegerField(blank=True, null=True)),
                ('accepted_name_code', models.CharField(blank=True, max_length=20, null=True)),
                ('status_id', models.IntegerField(blank=True, null=True)),
                ('is_endemic', models.IntegerField(blank=True, null=True)),
                ('alien_status', models.IntegerField(blank=True, null=True)),
                ('is_marine', models.IntegerField(blank=True, null=True)),
                ('is_fossil', models.IntegerField(blank=True, null=True)),
                ('ref_short', models.CharField(blank=True, max_length=200, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('datelastmodified', models.DateField(blank=True, null=True)),
                ('kingdom', models.CharField(blank=True, max_length=50, null=True)),
                ('kingdom_c', models.CharField(blank=True, max_length=50, null=True)),
                ('phylum', models.CharField(blank=True, max_length=50, null=True)),
                ('phylum_c', models.CharField(blank=True, max_length=50, null=True)),
                ('class_field', models.CharField(blank=True, db_column='class', max_length=50, null=True)),
                ('class_c', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.CharField(blank=True, max_length=50, null=True)),
                ('order_c', models.CharField(blank=True, max_length=50, null=True)),
                ('family', models.CharField(blank=True, max_length=50, null=True)),
                ('family_c', models.CharField(blank=True, max_length=50, null=True)),
                ('genus_c', models.CharField(blank=True, max_length=50, null=True)),
                ('common_name', models.CharField(blank=True, max_length=255, null=True)),
                ('alternative_name_c', models.TextField(blank=True, null=True)),
                ('iucn_code', models.CharField(blank=True, max_length=255, null=True)),
                ('cites_code', models.CharField(blank=True, max_length=255, null=True)),
                ('coa_redlist_code', models.CharField(blank=True, max_length=255, null=True)),
                ('redlist2017', models.CharField(blank=True, max_length=10, null=True)),
                ('redlist_wang', models.CharField(blank=True, max_length=255, null=True)),
                ('redlist_chen', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'view_apioutput',
                'managed': False,
            },
        ),
    ]
